spring.application.name=libreria2.0
# ===================================
# Configuración de Rendimiento (Java 21/26)
# ===================================
# Esto aprovecha los hilos virtuales de tu nuevo JDK
spring.threads.virtual.enabled=true

# Desactivamos esto para que funcione tu GlobalExceptionHandler personalizado
spring.mvc.problemdetails.enabled=false

# ===================================
# Conexión a PostgreSQL (NeonTech)
# ===================================
spring.datasource.url=jdbc:postgresql://ep-mute-lake-acd7ruyv-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_OBuTlLDCyi64
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate para desarrollo
# 'update' creará las tablas de tu modelo 'Libro' automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Pool de conexiones (Mantenerlo bajo para planes gratuitos de Neon)
spring.datasource.hikari.maximum-pool-size=3


 
springdoc.api-docs.enabled=true

 
springdoc.swagger-ui.enabled=true

 
springdoc.swagger-ui.path=/doc/swagger-ui.html